name             'mysql_cluster'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures mysql_cluster'
long_description 'Installs/Configures mysql_cluster'
version          '0.1.0'
